code: configure
parentCode: homepage
titles:
  en: Configure
  it: Configure
pageModel: 1-2-column
ownerGroup: administrators
# joinGroups:
#   - application_users
#   - business_users
#   - mgft_users
displayedInMenu: true
seo: false
charset: utf-8
status: published
widgets: []
